insert into AddressDetails (postalCode, streetName, city, province) values ('40546', '47 Bonner Park', 'Lexington', 'Kentucky');
insert into AddressDetails (postalCode, streetName, city, province) values ('31196', '21028 Mifflin Road', 'Atlanta', 'Georgia');
insert into AddressDetails (postalCode, streetName, city, province) values ('01129', '17 Norway Maple Crossing', 'Springfield', 'Massachusetts');
insert into AddressDetails (postalCode, streetName, city, province) values ('46239', '502 Warrior Point', 'Indianapolis', 'Indiana');
insert into AddressDetails (postalCode, streetName, city, province) values ('64082', '7 Rowland Lane', 'Lees Summit', 'Missouri');
insert into AddressDetails (postalCode, streetName, city, province) values ('36605', '930 International Drive', 'Mobile', 'Alabama');
insert into AddressDetails (postalCode, streetName, city, province) values ('33330', '2276 Redwing Alley', 'Fort Lauderdale', 'Florida');
insert into AddressDetails (postalCode, streetName, city, province) values ('22309', '943 Nancy Way', 'Alexandria', 'Virginia');
insert into AddressDetails (postalCode, streetName, city, province) values ('02905', '03 Mcbride Pass', 'Providence', 'Rhode Island');
insert into AddressDetails (postalCode, streetName, city, province) values ('60351', '3 Northridge Point', 'Carol Stream', 'Illinois');
insert into AddressDetails (postalCode, streetName, city, province) values ('44511', '45 Lakewood Parkway', 'Youngstown', 'Ohio');
insert into AddressDetails (postalCode, streetName, city, province) values ('78715', '4786 Manufacturers Plaza', 'Austin', 'Texas');
insert into AddressDetails (postalCode, streetName, city, province) values ('30328', '6369 Knutson Alley', 'Atlanta', 'Georgia');
insert into AddressDetails (postalCode, streetName, city, province) values ('94230', '5591 Mesta Terrace', 'Sacramento', 'California');
insert into AddressDetails (postalCode, streetName, city, province) values ('75062', '8347 Scoville Center', 'Irving', 'Texas');
insert into AddressDetails (postalCode, streetName, city, province) values ('80243', '65833 Sycamore Parkway', 'Denver', 'Colorado');
insert into AddressDetails (postalCode, streetName, city, province) values ('26505', '68 Granby Street', 'Morgantown', 'West Virginia');
insert into AddressDetails (postalCode, streetName, city, province) values ('81005', '039 South Trail', 'Pueblo', 'Colorado');
insert into AddressDetails (postalCode, streetName, city, province) values ('16522', '7881 Evergreen Pass', 'Erie', 'Pennsylvania');
insert into AddressDetails (postalCode, streetName, city, province) values ('74126', '12 Fisk Way', 'Tulsa', 'Oklahoma');
