insert into Facilities (fid, address, type) values (1, '54356 Bowman Street', 'Restaurant');
insert into Facilities (fid, address, type) values (2, '94 Redwing Way', 'Gym');
insert into Facilities (fid, address, type) values (3, '4 Caliangt Way', 'Shopping Mall');
insert into Facilities (fid, address, type) values (4, '8279 Anderson Terrace', 'Restaurant');
insert into Facilities (fid, address, type) values (5, '4 Ronald Regan Place', 'Shopping Mall');
insert into Facilities (fid, address, type) values (6, '1 Gina Pass', 'Gym');
insert into Facilities (fid, address, type) values (7, '631 Rockefeller Junction', 'Shopping Mall');
insert into Facilities (fid, address, type) values (8, '88 Washington Hill', 'Restaurant');
insert into Facilities (fid, address, type) values (9, '84 Graedel Way', 'Gym');
insert into Facilities (fid, address, type) values (10, '001 Memorial Hill', 'Shopping Mall');
insert into Facilities (fid, address, type) values (11, '26 Hermina Crossing', 'Gym');
insert into Facilities (fid, address, type) values (12, '45 Schurz Hill', 'Gym');
insert into Facilities (fid, address, type) values (13, '746 Scofield Lane', 'Restaurant');
insert into Facilities (fid, address, type) values (14, '82089 Bellgrove Road', 'Restaurant');
insert into Facilities (fid, address, type) values (15, '37 Miller Trail', 'Restaurant');
insert into Facilities (fid, address, type) values (16, '2393 Bellgrove Court', 'Shopping Mall');
insert into Facilities (fid, address, type) values (17, '518 Glacier Hill Alley', 'Shopping Mall');
insert into Facilities (fid, address, type) values (18, '20 Kim Circle', 'Shopping Mall');
insert into Facilities (fid, address, type) values (19, '03904 Hazelcrest Hill', 'Gym');
insert into Facilities (fid, address, type) values (20, '8 Helena Crossing', 'Restaurant');

